version: '3.9'

services:
  db:
    image: postgis/postgis
    restart: always
    container_name: database
    environment:
      POSTGRES_USER: test
      POSTGRES_PASSWORD: test
      POSTGRES_DB: postgres
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready" ]
      interval: 10s
      timeout: 5s
      retries: 5
  liquibase:
    image: test-liquibase:latest
    container_name: liquibase
    build:
      context: ./liquibase/
      dockerfile: Dockerfile
    command:
      - update
    environment:
      LIQUIBASE_LOG_LEVEL: "info"
      LIQUIBASE_COMMAND_CHANGELOG_FILE: "master.xml"
      LIQUIBASE_COMMAND_URL: jdbc:postgresql://database:5432/postgres
      LIQUIBASE_COMMAND_USERNAME: test
      LIQUIBASE_COMMAND_PASSWORD: test
    depends_on:
      db:
        condition: service_healthy
networks:
  default:
    name: test