version: '3.9'

services:
  db:
    image: postgis/postgis
    restart: always
    environment:
      - POSTGRES_USER=test
      - POSTGRES_PASSWORD=test
      - POSTGRES_DB=postgres
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready", "-U", "postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - infra
  liquibase:
    image: test-liquibase:latest
    build:
      context: ../liquibase
      dockerfile: ../liquibase/Dockerfile
    command:
      - update
    environment:
      LIQUIBASE_LOG_LEVEL: "info"
      LIQUIBASE_COMMAND_CHANGELOG_FILE: "master.xml"
      LIQUIBASE_COMMAND_URL: jdbc:postgresql://db:5432/postgres
      LIQUIBASE_COMMAND_USERNAME: test
      LIQUIBASE_COMMAND_PASSWORD: test
    networks:
      - infra
    depends_on:
      db:
        condition: service_healthy
  end-detector:
    image: hello-world
    depends_on:
      liquibase:
        condition: service_completed_successfully

networks:
  infra:
    external: false