/*
 * This file is generated by jOOQ.
 */
package org.example.database.model;


import org.example.database.model.tables.Car;


/**
 * Convenience access to all tables in public.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>public.car</code>.
     */
    public static final Car CAR = Car.CAR;
}
