/*
 * This file is generated by jOOQ.
 */
package org.example.database.model.tables.records;


import org.example.database.model.tables.Car;
import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record5;
import org.jooq.Row5;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class CarRecord extends UpdatableRecordImpl<CarRecord> implements Record5<Long, String, String, Double, Long> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.car.id</code>.
     */
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.car.id</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>public.car.make</code>.
     */
    public void setMake(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.car.make</code>.
     */
    public String getMake() {
        return (String) get(1);
    }

    /**
     * Setter for <code>public.car.brand</code>.
     */
    public void setBrand(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.car.brand</code>.
     */
    public String getBrand() {
        return (String) get(2);
    }

    /**
     * Setter for <code>public.car.price</code>.
     */
    public void setPrice(Double value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.car.price</code>.
     */
    public Double getPrice() {
        return (Double) get(3);
    }

    /**
     * Setter for <code>public.car.user_id</code>.
     */
    public void setUserId(Long value) {
        set(4, value);
    }

    /**
     * Getter for <code>public.car.user_id</code>.
     */
    public Long getUserId() {
        return (Long) get(4);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record5 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row5<Long, String, String, Double, Long> fieldsRow() {
        return (Row5) super.fieldsRow();
    }

    @Override
    public Row5<Long, String, String, Double, Long> valuesRow() {
        return (Row5) super.valuesRow();
    }

    @Override
    public Field<Long> field1() {
        return Car.CAR.ID;
    }

    @Override
    public Field<String> field2() {
        return Car.CAR.MAKE;
    }

    @Override
    public Field<String> field3() {
        return Car.CAR.BRAND;
    }

    @Override
    public Field<Double> field4() {
        return Car.CAR.PRICE;
    }

    @Override
    public Field<Long> field5() {
        return Car.CAR.USER_ID;
    }

    @Override
    public Long component1() {
        return getId();
    }

    @Override
    public String component2() {
        return getMake();
    }

    @Override
    public String component3() {
        return getBrand();
    }

    @Override
    public Double component4() {
        return getPrice();
    }

    @Override
    public Long component5() {
        return getUserId();
    }

    @Override
    public Long value1() {
        return getId();
    }

    @Override
    public String value2() {
        return getMake();
    }

    @Override
    public String value3() {
        return getBrand();
    }

    @Override
    public Double value4() {
        return getPrice();
    }

    @Override
    public Long value5() {
        return getUserId();
    }

    @Override
    public CarRecord value1(Long value) {
        setId(value);
        return this;
    }

    @Override
    public CarRecord value2(String value) {
        setMake(value);
        return this;
    }

    @Override
    public CarRecord value3(String value) {
        setBrand(value);
        return this;
    }

    @Override
    public CarRecord value4(Double value) {
        setPrice(value);
        return this;
    }

    @Override
    public CarRecord value5(Long value) {
        setUserId(value);
        return this;
    }

    @Override
    public CarRecord values(Long value1, String value2, String value3, Double value4, Long value5) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached CarRecord
     */
    public CarRecord() {
        super(Car.CAR);
    }

    /**
     * Create a detached, initialised CarRecord
     */
    public CarRecord(Long id, String make, String brand, Double price, Long userId) {
        super(Car.CAR);

        setId(id);
        setMake(make);
        setBrand(brand);
        setPrice(price);
        setUserId(userId);
        resetChangedOnNotNull();
    }
}
